- name: check namesrv deploy directory
  stat:
    path: "{{ rocketmq_deploy_path }}/rocketmq"
  register: deploy_directory

- debug:
    msg: "{{ deploy_directory }}"

- name: download rocketmq
  unarchive:
    src: "{{ rocketmq_download_url }}"
    dest: "{{ rocketmq_deploy_path }}"
    remote_src: yes
    mode: 0750
  when: deploy_directory.stat.exists == False

- name: rename rocketmq directory name
  shell: cd {{ rocketmq_deploy_path }}; if [ ! -d "rocketmq" ]; then mv rocketmq-* rocketmq; fi

- name: modify namesrv log path
  template:
    src: logback_namesrv.xml.j2
    dest: "{{ rocketmq_deploy_path }}/rocketmq/conf/logback_namesrv.xml"

- name: copy namesrv service script
  template:
    src: mqnamesrv.service
    dest: /usr/lib/systemd/system
    mode: 0750

- name: check namesrv process status
  shell: source /etc/profile && jps | grep NamesrvStartup | wc -l
  register: check_status

- debug:
    msg: "{{ check_status }}"

- name: start namesrv
  shell: |
    source /etc/profile
    systemctl disable mqnamesrv
    systemctl enable mqnamesrv
    systemctl stop mqnamesrv
    systemctl start mqnamesrv
  when: check_status.stdout|int == 0